name: Deploy to prod

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Make production envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_HCAPTCHA_SITEKEY: ${{ secrets.HCAPTCHA_SITEKEY }}
          envkey_VITE_API_URL: ${{ secrets.API_URL }}
          file_name: .env.local

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Sync files via SSH
      - name: Copy files via ssh and rsync
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags: -avzr --delete
          excludes: ""
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          localpath: "./"
          remotepath: ${{ secrets.REMOTE_TARGET }}
          deploy_key: ${{ secrets.SERVER_SSH_KEY }}
